// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/tuna#two

extern const LV2_Descriptor* lv2_descriptor(uint32_t index);
extern const LV2UI_Descriptor* lv2ui_descriptor(uint32_t index);

static const RtkLv2Description _plugin_tuna_two = {
	&lv2_descriptor,
	&lv2ui_descriptor
	, 2 // uint32_t dsp_descriptor_id
	, 0 // uint32_t gui_descriptor_id
	, "Instrument Tuner[Spectrum]" // const char *plugin_human_id
	, (const struct LV2Port[20])
	{
		{ "control", ATOM_IN, nan},
		{ "notify", ATOM_OUT, nan},
		{ "in", AUDIO_IN, nan},
		{ "out", AUDIO_OUT, nan},
		{ "mode", CONTROL_IN, 0.000000},
		{ "tuning", CONTROL_IN, 440.000000},
		{ "rms", CONTROL_OUT, nan},
		{ "freq_out", CONTROL_OUT, nan},
		{ "octave", CONTROL_OUT, nan},
		{ "note", CONTROL_OUT, nan},
		{ "cent", CONTROL_OUT, nan},
		{ "accuracy", CONTROL_OUT, nan},
		{ "strobetoui", CONTROL_OUT, nan},
		{ "thresholdRMS", CONTROL_IN, -75.000000},
		{ "thresholdPostFilter", CONTROL_IN, -45.000000},
		{ "thresholdFFT", CONTROL_IN, -40.000000},
		{ "thresholdOverride", CONTROL_IN, 20.000000},
		{ "thresholdFundamental", CONTROL_IN, 5.000000},
		{ "thresholdOctave", CONTROL_IN, -30.000000},
		{ "thresholdOvertones", CONTROL_IN, -15.000000},
	}
	, 20 // uint32_t nports_total
	, 1 // uint32_t nports_audio_in
	, 1 // uint32_t nports_audio_out
	, 0 // uint32_t nports_midi_in
	, 0 // uint32_t nports_midi_out
	, 1 // uint32_t nports_atom_in
	, 1 // uint32_t nports_atom_out
	, 16 // uint32_t nports_ctrl
	, 9 // uint32_t nports_ctrl_in
	, 7 // uint32_t nports_ctrl_out
	, 8192 // uint32_t min_atom_bufsiz
	, false // bool send_time_info
};

#ifdef X42_PLUGIN_STRUCT
#undef X42_PLUGIN_STRUCT
#endif
#define X42_PLUGIN_STRUCT _plugin_tuna_two
